//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i2SWhereRU_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public Map()
        {
            this.Persons = new HashSet<Person>();
        }
    
        public int m_id { get; set; }
        public string m_description { get; set; }
        public string m_image_location { get; set; }
    
        public virtual ICollection<Person> Persons { get; set; }
    }
}
