//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i2SWhereRU_WS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int p_id { get; set; }
        public string p_name { get; set; }
        public string p_image_location { get; set; }
        public string p_location_city { get; set; }
        public int p_location_map_id { get; set; }
        public int p_location_station_id { get; set; }
    
        public virtual Map Map { get; set; }
        public virtual Station Station { get; set; }
    }
}
